### PR TITLE
Added install and run instructions

### PR DESCRIPTION
**Pull request by heftymouse**
I reset my fork and then re-added INSTALL.md, here's the new PR.

### CODE REVIEW

**Comment by devcer** [comment]
@heftymouse This looks good. Can you update your master branch and also sign all your commits so that I can merge this?

**Comment by heftymouse** [comment]
Sure, will do.

**Comment by heftymouse** [comment]
Done! I've signed my commit.

**Review by devcer — APPROVED** [review]

**Comment by devcer** [comment]
@heftymouse I see many commits are not signed yet and I'm unable to merge your changes. Maybe you could squash the commits into one and then sign it?

**Comment by heftymouse** [comment]
@devcer I'm sorry for removing your review. I reset the fork back to its state when I first made the PR, and then signed and updated it. I'd made a complete mess out of trying to squash it to the point where this was the only option left for me. Hopefully it's now in a state fit for merging.

**Review by devcer — APPROVED** [review]

**Comment by devcer** [comment]
Merged. Thank you! Happy Hacktoberfest.

**Pull request merged**
